Add API function useAbility
LukeAngove/cpp_rpg pull request #9
Opened 2022-10-17 11:44 UTC by nicole-angove

2022-10-19 10:12 UTC, LukeAngove requested changes
Minor changes requested, just fixing white-space and adding some documentation.

2022-10-19 10:12 UTC, LukeAngove commented on BUILD
> +)
Missing newline at end of file, please add it.

2022-10-19 10:12 UTC, LukeAngove commented on api.h
> +bool useAbility(int abilityID);
This is a public API function, so it should have documentation explaining what it is, what it does and what the parameters are. For example, start with something like:
```suggestion
/**
 * Tries to use the given ability.
 * 
 * Returns false if the ability cannot be used.
 */
bool useAbility(int abilityID);
```

2022-10-19 10:12 UTC, LukeAngove commented on api.h
> +bool useAbility(int abilityID);
See https://google.github.io/styleguide/cppguide.html#Function_Comments for some good guidelines.

2022-10-19 10:12 UTC, LukeAngove commented on apitest.cpp
> +
Remove this empty line.

2023-01-20 08:55 UTC, LukeAngove approved these changes

2023-02-01 08:42 UTC, Johjahn1 approved these changes

2023-02-01 08:44 UTC, merged